// frontend/src/pages/Buy.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { tg } from '../tg';
import AmountPicker from '../components/AmountPicker';
import { purchase } from '../api';

export default function Buy() {
  const [amount, setAmount] = useState(0);
  const navigate = useNavigate();

  function confirm() {
    const userId = tg.initDataUnsafe?.user?.id;
    if (!userId || amount < 1) return;
    purchase(userId, amount).then(res => {
      if (res.ok) navigate('/success');
      else alert(res.error);
    });
  }

  return (
    <div className="container">
      <AmountPicker onSelect={setAmount} />
      <button className="btn" onClick={confirm}>Купить</button>
    </div>
  );
}

// frontend/src/pages/Buy.svelte
<script>
  import AmountPicker from "../components/AmountPicker.svelte";
  import LoadingOverlay from "../components/LoadingOverlay.svelte";
  import { purchase } from "../api.js";
  import { navigate } from "../router.js";
  import { tg } from "../tg.js";
  const PRICE_USD = 0.05;
  let amount = 0;
  let loading = false;

  async function confirm() {
    const userId = tg.initDataUnsafe?.user?.id;
    if (!userId || amount < 1) return;
    loading = true;
    await new Promise(r => setTimeout(r, 2000));
    const tx = {
      amount,
      fiat: amount * PRICE_USD,
      time: Date.now()
    };
    const history = JSON.parse(localStorage.getItem('history') || '[]');
    history.push(tx);
    localStorage.setItem('history', JSON.stringify(history));
    localStorage.setItem('lastPurchase', JSON.stringify(tx));
    loading = false;
    navigate('/success');
  }
</script>

<div class="container">
  <h2><button class="btn" on:click={() => navigate("/")}>🢀</button> Сколько желаете?</h2>
  <AmountPicker onSelect={(val) => (amount = val)} />

  <button style="margin-top: 8px;" class="btn" on:click={confirm} disabled={loading}>Купить</button>
</div>

{#if loading}
  <LoadingOverlay />
{/if}
