// frontend/src/pages/Gift.jsx
import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { tg } from '../tg';
import AmountPicker from '../components/AmountPicker';
import UsernameDisplay from '../components/UsernameDisplay';
import { gift } from '../api';

export default function Gift() {
  const [amount, setAmount] = useState(0);
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const toId = params.get('user_id');

  function confirm() {
    const fromId = tg.initDataUnsafe?.user?.id;
    if (!fromId || !toId || amount < 1) return;
    gift(fromId, parseInt(toId, 10), amount).then(res => {
      if (res.ok) navigate('/success');
      else alert(res.error);
    });
  }

  return (
    <div className="container">
      <UsernameDisplay username={toId} />
      <AmountPicker onSelect={setAmount} />
      <button className="btn" onClick={confirm}>Подарить</button>
    </div>
  );
}

// frontend/src/pages/Gift.svelte
<script>
  import AmountPicker from '../components/AmountPicker.svelte';
  import UsernameDisplay from '../components/UsernameDisplay.svelte';
  import { navigate } from '../router.js';
  import { tg } from '../tg.js';
  import { gift } from '../api.js';
  import RippleButton from '../components/RippleButton.svelte';

  let amount = 0;
  const params = new URLSearchParams(window.location.search);
  const toId = params.get('user_id');

  function confirm() {
    const fromId = tg.initDataUnsafe?.user?.id;
    if (!fromId || !toId || amount < 1) return;
    gift(fromId, parseInt(toId, 10), amount).then(res => {
      if (res.ok) navigate('/success');
      else alert(res.error);
    });
  }
</script>

<div class="container">
  <UsernameDisplay username={toId} />
  <AmountPicker onSelect={val => amount = val} />
  <RippleButton onClick={confirm}>Подарить</RippleButton>
</div>
