// frontend/src/App.jsx
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { useEffect } from 'react';
import { initTelegram } from './tg';
import Welcome from './pages/Welcome';
import Buy from './pages/Buy';
import Gift from './pages/Gift';
import Success from './pages/Success';
import './index.css';

export default function App() {
  useEffect(() => {
    initTelegram();
  }, []);

  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Welcome />} />
        <Route path="/buy" element={<Buy />} />
        <Route path="/gift" element={<Gift />} />
        <Route path="/success" element={<Success />} />
      </Routes>
    </BrowserRouter>
  );
}

// frontend/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { route } from './router.js';
  import { initTelegram } from './tg.js';
  import Welcome from './pages/Welcome.svelte';
  import Buy from './pages/Buy.svelte';
  import Gift from './pages/Gift.svelte';
  import Success from './pages/Success.svelte';

  let current = window.location.pathname || '/';

  const pages = {
    '/': Welcome,
    '/buy': Buy,
    '/gift': Gift,
    '/success': Success
  };

  onMount(() => {
    initTelegram();
    return route.subscribe(v => current = v);
  });

  $: Component = pages[current] || Welcome;
</script>

<svelte:component this={Component} />
